//Action type
export const TOGGLE_LOGON = 'TOGGLE_LOGON';

export const REQUEST_DEPARTMENT = 'REQUEST_DEPARTMENT';

export const RECEIVE_DEPARTMENT = 'RECEIVE_DEPARTMENT';

export const REQUEST_PROFILE = 'REQUEST_PROFILE';

export const RECEIVE_PROFILE = 'RECEIVE_PROFILE';

export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const START_UPLOAD = 'START_UPLOAD';

export const FINISH_UPLOAD = 'FINISH_UPLOAD';